### PR TITLE
8f63167 CHART: add additionalProperties for falco-exporter service Monitor

### PR DESCRIPTION
**Pull request by ArnaudCHT**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

/kind feature

> If this PR will release a new chart version please make sure to also uncomment the following line:

/kind chart-release

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area falco-chart

/area falco-exporter-chart

> /area falcosidekick-chart

> /area event-generator-chart

> /area k8s-metacollector

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
I've added the capability to the Falco-exporter charts to set additional properties within the Service Monitor, such as relabelings, metricRelabelings, etc.
I ran a Helm template and tested the Service Monitor in an OpenShift cluster.

commit : 8f6316779caea99066e2e535d8b0b7df5dba7650

**Checklist**

- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] CHANGELOG.md updated

### CODE REVIEW

**Review by Issif — DISMISSED** [review]
Seems all good to me. Thanks

**Comment by Issif** [comment]
Can you sign off your commits and run `make docs` to format the readme as expected please.

**Comment by ArnaudCHT** [comment]
Hello, I sign off the commits and run `make docs`. Thanks.

**Comment by Issif** [comment]
This DCO is still wrong, are you sure having signed off the commit?

**Comment by ArnaudCHT** [comment]
My bad. This should be OK now !

**Review by Issif — APPROVED** [review]

**Pull request merged**
