### PR TITLE
Fix: labels for Falcosidekick

### PR DESCRIPTION
**Pull request by nlamirault**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> If this PR will release a new chart version please make sure to also uncomment the following line:

> /kind chart-release

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area falco-chart

> /area falco-exporter-chart

/area falcosidekick-chart

> /area event-generator-chart

**What this PR does / why we need it**:

We can't generate PrometheusRule resources:

``` 
helm template charts/falcosidekick --set prometheusRules.enabled=true --set serviceMonitor.enabled=true
Error: template: falcosidekick/templates/prometheusrule.yaml:10:8: executing "falcosidekick/templates/prometheusrule.yaml" at <include "falcosidekick.labels" .>: error calling include: template: no template "falcosidekick.labels" associated with template "gotpl"

Use --debug flag to render out invalid YAML
```

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Checklist**

- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] CHANGELOG.md updated

### CODE REVIEW

**Comment by Issif** [comment]
Why have you created the #563 and #564 for the same changes?

Moreover, you need to update the version in the Chart.yaml and the Changelog to pass the CI.

**Comment by nlamirault** [comment]
@Issif this one is to fix the bug when I enable observability for Sidekick UI components
https://github.com/falcosecurity/charts/pull/563 is a refactoring of label management.

**Comment by Issif** [comment]
> @Issif this one is to fix the bug when I enable observability for Sidekick UI components #563 is a refactoring of label management.

Ok, can you merge them for having only 1 PR please?

**Comment by mmadoo** [comment]
I need this PR for my deployment, any idea when it will be merged ?
Can I help on this subject ?

**Comment by Issif** [comment]
> I need this PR for my deployment, any idea when it will be merged ? Can I help on this subject ?

Hi,

As I said in the #563, you need to update the Chart.yaml and Changelog.md to pass the CI. The #563 must be merged before this one, right?

**Comment by mmadoo** [comment]
This PR includes changes from #563.
I add the commit https://github.com/DCbrainOrg/falco-charts/commit/4a857aa5feeb102e736fc60408135748ca09a396  but on the repository [DCbrainOrg:fix/falcosidekick-labels](https://github.com/DCbrainOrg/falco-charts/tree/fix/falcosidekick-labels) 
Should I create a new pull request or do you want to update pull request source ?

**Comment by Issif** [comment]
What I see is: the #563 contains the changes of the #564. The #564 is not valid, because you forgot to update the Chart.yaml and the Changelog.md.

I think we can close thise PR #564 and follow up in the #563 which is more complete.

**Comment by Issif** [comment]
I'm closing this PR cause #588 has been merged

**Pull request closed without merging**
