### PR TITLE
fix: `/etc` mount, `--cri` flag path, and bump Falco to 0.23.0

### LINKED ISSUE #9: Helm install for falco not working on EKS 1.16 -- Unable to download precompiled falco-probe module for 4.14.173-137.229.amzn2.x86_64
**Describe the bug**
We recently updated from EKS 1.15 to 1.16. We were using `0.19.0` of Falco before this without issue.
We tried using the latest `falcosecurity/falco:master` image, but that did not resolve the issue.

```
Error! echo
Your kernel headers for kernel 4.14.173-137.229.amzn2.x86_64 cannot be found at
/lib/modules/4.14.173-137.229.amzn2.x86_64/build or /lib/modules/4.14.173-137.229.amzn2.x86_64/source.
* Running dkms build failed, couldn't find /var/lib/dkms/falco/a259b4bf49c3330d9ad6c3eed9eb1a31954259a6/build/make.log
* Trying to load a system falco-probe, if present
* Trying to find precompiled falco-probe for 4.14.173-137.229.amzn2.x86_64
Found kernel config at /host/boot/config-4.14.173-137.229.amzn2.x86_64
* Trying to download precompiled module from https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/falco-probe-a259b4bf49c3330d9ad6c3eed9eb1a31954259a6-x86_64-4.14.173-137.229.amzn2.x86_64-f0c8ced41ae4d0e71aa715068964ce9f.ko
curl: (22) The requested URL returned error: 404 Not Found
Download failed, consider compiling your own falco-probe and loading it or getting in touch with the Falco community
Tue May  5 15:09:32 2020: Falco initialized with configuration file /etc/falco/falco.yaml
Tue May  5 15:09:32 2020: Loading rules from file /etc/falco/falco_rules.yaml:
Tue May  5 15:09:32 2020: Loading rules from file /etc/falco/falco_rules.local.yaml:
Tue May  5 15:09:33 2020: Unable to load the driver. Exiting.
Tue May  5 15:09:33 2020: Runtime error: error opening device /host/dev/falco0. Make sure you have root credentials and that the falco-probe module is loaded.. Exiting.
```

**How to reproduce it**

`helm install falcohelm stable/falco` in the EKS 1.16 env.

**Expected behaviour**

No errors when Falco pods spin up.

**Environment**

- Falco version:

`0.18.0` /  `0.19.0` /  `0.22.0` /  `master`

- Cloud provider or hardware configuration: EKS cluster (`1.16`)
- OS: Amazon Linux 2
- Installation method: Helm Install

### PR DESCRIPTION
**Pull request by leogr**
Fixes #9

As per https://github.com/falcosecurity/falco/issues/1203 and [the official documentation](https://falco.org/docs/running/#docker-privileged) (see `-v /etc:/host/etc:ro`)

/cc @nibalizer 

/kind bug

### CODE REVIEW

**Comment by leogr** [comment]
> But, what about verifying the `HOST_ROOT` env variable too?
> Some references:
> 
> * [falcosecurity/falco#1140](https://github.com/falcosecurity/falco/pull/1140)
> * https://github.com/falcosecurity/falco/pull/1133/files


I'm already investigating that, but it seems to be a different problem. 
I tried the helm chart and inside the container, `HOST_ROOT=/host` is set properly (I guess because of [this](https://github.com/falcosecurity/falco/blob/434a5abc8b7b79a873617f8d3eddf9b1f69a0222/docker/falco/Dockerfile#L12)). So why should we fix it in the helm chart?

**Comment by leogr** [comment]
@leodido I have got now, you were referring to [this](https://github.com/falcosecurity/charts/blob/62087f553a6928000ac315b77ad9fb7607a9dd25/falco/templates/daemonset.yaml#L58). I have to test it, then I will fix it

**Comment by leodido** [comment]
Yes, the `--cri` should have the value without `/host` prefix

**Comment by leogr** [comment]
> Yes, the `--cri` should have the value without `/host` prefix

Done by https://github.com/falcosecurity/charts/pull/10/commits/793348198eaea046a5a8d25c2aa8dbf6060b67a8

**Comment by nibalizer** [comment]
Looks good to me

/approve

**Pull request merged**
