### PR TITLE
Filter out easy alerts and updated the rules to k8s_containers & postgres_running_wal_e

### PR DESCRIPTION
**Pull request by raviranjanelastisys**
Signed-off-by: Ravi Ranjan <ravi.ranjan@elastisys.com>

**What type of PR is this?**

 /kind feature

**Any specific area of the project related to this PR?**

 /area falco-chart

**What this PR does / why we need it**:

Bases on our investigations and finding , Contact K8S API Server From Container" should be ignored for container images which are known "controllers".

**Which issue(s) this PR fixes**:
N/A

Fixes #

**Special notes for your reviewer**:

This issue consists in filtering a few "obvious" false-positives.
Contact K8S API Server From Container" should be ignored for container images which are known "controllers".

**Checklist**

- [X] Chart Version bumped
- [ ] Variables are documented in the README.md
- [X] CHANGELOG.md updated

### CODE REVIEW

**Comment by raviranjanelastisys** [comment]
@nestorsalceda Hi , Any update on this PR ?

**Comment by leogr** [comment]
Hey @raviranjanelastisys 

Same as the other PR, rules changes must happen directly in the [falco repository](https://github.com/falcosecurity/falco/tree/master/rules). :)

So could you open a PR there, please?

Thank you again for your time :pray: 

/close

**Comment by raviranjanelastisys** [comment]
@leogr Thanks !! I will open the PR in the repository suggested by you . thanks

**Comment by raviranjanelastisys** [comment]
Opened the PR against the correct repos as suggested - https://github.com/falcosecurity/falco/pull/1981

**Pull request closed without merging**
