### PR TITLE
Add DATADOG_HOST to secret

### PR DESCRIPTION
**Pull request by phillebaba**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> If this PR will release a new chart version please make sure to also uncomment the following line:

> /kind chart-release

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area falco-chart

> /area falco-exporter-chart

/area falcosidekick-chart

**What this PR does / why we need it**:

Adds the value for `config.datadog.host` to the secret created by the chart. If this is not done the value will have no effect on falcosidekick.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Checklist**

- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] CHANGELOG.md updated

### CODE REVIEW

**Review by Issif — COMMENTED** [review]
Thank for the fix.

Can you update the changelog and bump up the version of chart please.

**Review by Issif — DISMISSED** [review]

**Comment by Issif** [comment]
🙏 thank you

**Review by leogr — DISMISSED** [review]
Thank you for your contribution!

Since another PR got merged in meanwhile, I had to rebase and bumped the version to 0.2.4. And approved again :+1: 
It should get merged as soon as the Github checks became all green :)

**Comment by Issif** [comment]
@phillebaba The lint is not OK, can you take a look please : https://app.circleci.com/pipelines/github/falcosecurity/charts/369/workflows/dff17068-0e0a-43d2-b063-a3f70d4ef953/jobs/544

**Comment by leogr** [comment]
> @phillebaba The lint is not OK, can you take a look please:
> 
> ```
> [ERROR] templates/: template: falcosidekick/templates/secrets.yaml:48:50: executing "falcosidekick/templates/secrets.yaml" at <b64enc>: invalid value; expected string
> ```

I have added `host` within `values.yaml` that should fix the lint issue.

**Review by Issif — APPROVED** [review]

**Comment by phillebaba** [comment]
@leogr thanks for fixing it :)

**Review by leogr — APPROVED** [review]

**Pull request merged**
