### PR TITLE
add support for configuring the updateStrategy of the falco-exporter ds

### PR DESCRIPTION
**Pull request by Kostavro**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

/kind feature

> If this PR will release a new chart version please make sure to also uncomment the following line:

/kind chart-release

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area falco-chart

/area falco-exporter-chart

> /area falcosidekick-chart

**What this PR does / why we need it**:
This PR adds support for configuring the falco-exporter DaemonSet updateStrategy, via a similar block as already exists for the falco DaemonSet.

**Which issue(s) this PR fixes**:
The current falco-exporter chart does not support editing the default DaemonSet updateStrategy.

Fixes #

**Special notes for your reviewer**:

**Checklist**

- [X] Chart Version bumped
- [ ] Variables are documented in the README.md
- [X] CHANGELOG.md updated

### CODE REVIEW

**Comment by Kostavro** [comment]
e2e tests failing - same as in https://github.com/falcosecurity/charts/pull/334 - discussion is there.

**Comment by leogr** [comment]
> > e2e tests failing - same as in #334 - discussion is there.
> 
> Just rebased. It should work now.

Quick update: something still went wrong; trying to fix.

**Comment by Kostavro** [comment]
@leogr there is probably not much I can do to help, but please let me know if I can, in any way :)

**Comment by leogr** [comment]
Update: a fix for the CI is in the making :point_down: 
https://github.com/falcosecurity/charts/pull/354

**Review by leogr — APPROVED** [review]
I apologize for the CI fix that took so long. Now everything is addressed. :+1: 

Thank you for this PR, and sorry again for the inconvenience. :pray:

**Comment by cpanato** [comment]
sorry that was on me

**Comment by Kostavro** [comment]
No worries! Thank you both :)

**Pull request merged**
