### PR TITLE
chore: trigger CI again

### PR DESCRIPTION
**Pull request by leogr**
Signed-off-by: Leonardo Grasso <me@leonardograsso.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> If this PR will release a new chart version please make sure to also uncomment the following line:

> /kind chart-release

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area falco-chart

> /area falco-exporter-chart

> /area falcosidekick-chart

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

Almost empty PR, just to trigger the CI again since it broke:
https://app.circleci.com/pipelines/github/falcosecurity/charts/433/workflows/6cbecac5-9bed-4159-b9d9-76c3146fb33f/jobs/681

**Checklist**

- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] CHANGELOG.md updated

### CODE REVIEW

**Review by cpanato — COMMENTED** [review]
but you can retrigger the job manually, don't you?

**Review by cpanato — COMMENTED** [review]
/lgtm

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by leogr** [comment]
> but you can retrigger the job manually, don't you?

unfortunately, I can't. An internal error happened on circleci :(

**Pull request merged**
