### PR TITLE
[falcosidekick] From Azure identity >=1.6.0 CRD on fields are case sensitive

### PR DESCRIPTION
**Pull request by Annegies**
**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area falco-chart

> /area falco-exporter-chart

/area falcosidekick

**What this PR does / why we need it**:
From Azure pod identity 1.6.0 en onward CRD fields are case sensitive and must be camelcase.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Checklist**

- [x] Chart Version bumped

### CODE REVIEW

**Comment by Annegies** [comment]
The CONTRIBUTING.md is missing i'm afraid. Do you have a doc in another project with instruction the sign my commit with. the DCO signoff?

**Comment by leogr** [comment]
> The CONTRIBUTING.md is missing i'm afraid. Do you have a doc in another project with instructions the sign my commit with the DCO signoff?

Hey @Annegies 

You can find the CONTRIBUTING.md [here](https://github.com/falcosecurity/.github/blob/master/CONTRIBUTING.md).

Anyway you can just amend and sign-off your commit by: 
```
git commit --amend --signoff
```
Then, to update your branch
```
git push --force
```

I hope that can help.

Finally, I'm cc'ing @Issif since this PR is about falcosidekick

**Comment by Annegies** [comment]
Added the signoff

**Review by leogr — APPROVED** [review]
LGTM too

Thank you for your contribution!

**Pull request merged**
