### PR TITLE
fix: priority level "info" to "informational"

### PR DESCRIPTION
**Pull request by kirin-13**
Signed-off-by: kirin-13 <kirin_13@163.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> If this PR will release a new chart version please make sure to also uncomment the following line:

> /kind chart-release

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area falco-chart

> /area falco-exporter-chart

> /area falcosidekick-chart

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Checklist**

- [x] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] CHANGELOG.md updated

### CODE REVIEW

**Review by leogr — COMMENTED** [review]
Good catch!

Would you like to fix that also here :point_down: ?
https://github.com/falcosecurity/falco/blob/master/falco.yaml#L92-L95

**Comment by leogr** [comment]
Closing and reopening to trigger the CI
/close

**Review by leogr — COMMENTED** [review]
Hey @kirin-13

Could you bump the chart version, please? :pray: 

Our CI needs that to automatically publish the new chart. 

Otherwise, SGTM.

**Comment by kirin-13** [comment]
hi @leogr 
Updated charts version, please re-review. 🙏

**Comment by leogr** [comment]
Closing and reopening to trigger the CI
/close

**Review by leogr — APPROVED** [review]
/approve

**Pull request merged**
