### PR TITLE
feat(falcosidekick)!: support Ingress API version networking.k8s.io/v1

### LINKED ISSUE #273: [falcosidekick] Upgrade Ingress to networking.k8s.io/v1
**Describe the bug**

In k8s 1.22 the [currently used](https://github.com/falcosecurity/charts/blob/master/falcosidekick/templates/ingress.yaml#L4) API version for the falcosidekick Ingress resource is [removed](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122). As of k8s 1.22 deploying the chart fails.

### PR DESCRIPTION
**Pull request by sboschman**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

/kind feature

> If this PR will release a new chart version please make sure to also uncomment the following line:

/kind chart-release

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area falco-chart

> /area falco-exporter-chart

/area falcosidekick-chart

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #273

**Special notes for your reviewer**:

```
$ helm version
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

Kubernetes <= 1.17:
```
$ helm template --namespace falcosidekick --name-template falcosidekick -s templates/ingress.yaml -s templates/ingress-ui.yaml --set ingress.enabled=true --set ingress.hosts[0].host=sidekick.falco.org --set ingress.hosts[0].paths[0].path=/ --set webui.enabled=true --set webui.ingress.enabled=true --kube-version 1.17 .
---
# Source: falcosidekick/templates/ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: falcosidekick
  namespace: falcosidekick
  labels:
    app.kubernetes.io/name: falcosidekick
    helm.sh/chart: falcosidekick-0.3.17
    app.kubernetes.io/instance: falcosidekick
    app.kubernetes.io/managed-by: Helm
spec:
  rules:
    - host: "sidekick.falco.org"
      http:
        paths:
        - path: /
          backend:
            serviceName: falcosidekick
            servicePort: http
---
# Source: falcosidekick/templates/ingress-ui.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: falcosidekick-ui
  namespace: falcosidekick
  labels:
    app.kubernetes.io/name: falcosidekick-ui
    helm.sh/chart: falcosidekick-0.3.17
    app.kubernetes.io/instance: falcosidekick-ui
    app.kubernetes.io/managed-by: Helm
spec:
  rules:
    - host: "falcosidekick-ui.local"
      http:
        paths:
        - path: /ui
          backend:
            serviceName: falcosidekick-ui
            servicePort: http
        - path: /events
          backend:
            serviceName: falcosidekick-ui
            servicePort: http
        - path: /healthz
          backend:
            serviceName: falcosidekick-ui
            servicePort: http
        - path: /ws
          backend:
            serviceName: falcosidekick-ui
            servicePort: http
```

Kubernetes 1.18 (supports pathType with an implicit default, from 1.19 the pathType field in mandatory):
```
$ helm template --namespace falcosidekick --name-template falcosidekick -s templates/ingress.yaml -s templates/ingress-ui.yaml --set ingress.enabled=true --set ingress.hosts[0].host=sidekick.falco.org --set ingress.hosts[0].paths[0].path=/ --set webui.enabled=true --set webui.ingress.enabled=true --kube-version 1.18 .
---
# Source: falcosidekick/templates/ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: falcosidekick
  namespace: falcosidekick
  labels:
    app.kubernetes.io/name: falcosidekick
    helm.sh/chart: falcosidekick-0.3.17
    app.kubernetes.io/instance: falcosidekick
    app.kubernetes.io/managed-by: Helm
spec:
  rules:
    - host: "sidekick.falco.org"
      http:
        paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            serviceName: falcosidekick
            servicePort: http
---
# Source: falcosidekick/templates/ingress-ui.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: falcosidekick-ui
  namespace: falcosidekick
  labels:
    app.kubernetes.io/name: falcosidekick-ui
    helm.sh/chart: falcosidekick-0.3.17
    app.kubernetes.io/instance: falcosidekick-ui
    app.kubernetes.io/managed-by: Helm
spec:
  rules:
    - host: "falcosidekick-ui.local"
      http:
        paths:
        - path: /ui
          pathType: ImplementationSpecific
          backend:
            serviceName: falcosidekick-ui
            servicePort: http
        - path: /events
          pathType: ImplementationSpecific
          backend:
            serviceName: falcosidekick-ui
            servicePort: http
        - path: /healthz
          pathType: ImplementationSpecific
          backend:
            serviceName: falcosidekick-ui
            servicePort: http
        - path: /ws
          pathType: ImplementationSpecific
          backend:
            serviceName: falcosidekick-ui
            servicePort: http
```

Kubernetes 1.19+:
```
$ helm template --namespace falcosidekick --name-template falcosidekick -s templates/ingress.yaml -s templates/ingress-ui.yaml --set ingress.enabled=true --set ingress.hosts[0].host=sidekick.falco.org --set ingress.hosts[0].paths[0].path=/ --set webui.enabled=true --set webui.ingress.enabled=true --kube-version 1.19 .
---
# Source: falcosidekick/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: falcosidekick
  namespace: falcosidekick
  labels:
    app.kubernetes.io/name: falcosidekick
    helm.sh/chart: falcosidekick-0.3.17
    app.kubernetes.io/instance: falcosidekick
    app.kubernetes.io/managed-by: Helm
spec:
  rules:
    - host: "sidekick.falco.org"
      http:
        paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: falcosidekick
              port:
                name: http
---
# Source: falcosidekick/templates/ingress-ui.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: falcosidekick-ui
  namespace: falcosidekick
  labels:
    app.kubernetes.io/name: falcosidekick-ui
    helm.sh/chart: falcosidekick-0.3.17
    app.kubernetes.io/instance: falcosidekick-ui
    app.kubernetes.io/managed-by: Helm
spec:
  rules:
    - host: "falcosidekick-ui.local"
      http:
        paths:
        - path: /ui
          pathType: ImplementationSpecific
          backend:
            service:
              name: falcosidekick-ui
              port:
                name: http
        - path: /events
          pathType: ImplementationSpecific
          backend:
            service:
              name: falcosidekick-ui
              port:
                name: http
        - path: /healthz
          pathType: ImplementationSpecific
          backend:
            service:
              name: falcosidekick-ui
              port:
                name: http
        - path: /ws
          pathType: ImplementationSpecific
          backend:
            service:
              name: falcosidekick-ui
              port:
                name: http
```

**Checklist**

- [x] Chart Version bumped
- [x] CHANGELOG.md updated

### CODE REVIEW

**Review by Issif — CHANGES_REQUESTED** [review]
Helm template seems OK for me. Can you update the Chart.yaml and Changelog.md please. Without a bump of of the chart version, the CI will refuse to merge.

Can you also embed this fix please: https://gitlab.qonto.co/devops/kubernetes-resources/kyverno-policies/-/merge_requests/15

**Comment by sboschman** [comment]
New chart version is 1.0.0 following semver with a breaking change or ?

Just having a bit of a fight with CircleCI atm, I want to see the failing test results, without giving CircleCI read/write permissions to my entire github or bitbucket account!
They are insane imo requesting those permissions, they don't need those permissions for pure authentication against a github or bitbucket account and they for sure do not need those permissions to show me some test results for a public repo (which I do not even own).

> We ask for read/write access to make your experience seamless on CircleCI.

Requesting:
> Administer your repositories
> Read and modify your repositories

no way in hell, sorry

**Comment by sboschman** [comment]
> Can you also embed this fix please: https://gitlab.qonto.co/devops/kubernetes-resources/kyverno-policies/-/merge_requests/15

I can't access that site/gitlab instance:
```
$ nslookup gitlab.qonto.co; curl https://gitlab.qonto.co
Non-authoritative answer:
gitlab.qonto.co canonical name = gitlab-external-elb-1924446322.eu-west-3.elb.amazonaws.com.
Name:   gitlab-external-elb-1924446322.eu-west-3.elb.amazonaws.com
Address: 15.188.4.45
Name:   gitlab-external-elb-1924446322.eu-west-3.elb.amazonaws.com
Address: 15.188.186.193

curl: (28) Failed to connect to gitlab.qonto.co port 443: Connection timed out
```

**Comment by Issif** [comment]
@sboschman and you will never, I f*** up my copy/paste, sorry.

I was talking about #267

**Comment by sboschman** [comment]
> @sboschman and you will never, I f*** up my copy/paste, sorry.
> 
> I was talking about #267

```
 ✖︎ falco => (version: "1.15.7", path: "falco") > Chart version not ok. Needs a version bump!
 ✔︎ falcosidekick => (version: "0.4.0", path: "falcosidekick")
 ```
 
Not sure this is the right way @Issif to do this. #267 is a falco chart change, not a falcosidekick chart change. Seems I have to bump the falco chart version as well. Isn't it clearer to embed #267 in a PR for the falco chart to keep commits and merges separate?

**Comment by Issif** [comment]
> > @sboschman and you will never, I f*** up my copy/paste, sorry.
> > I was talking about #267
> 
> ```
>  ✖︎ falco => (version: "1.15.7", path: "falco") > Chart version not ok. Needs a version bump!
>  ✔︎ falcosidekick => (version: "0.4.0", path: "falcosidekick")
> ```
> 
> Not sure this is the right way @Issif to do this. #267 is a falco chart change, not a falcosidekick chart change. Seems I have to bump the falco chart version as well. Isn't it clearer to embed #267 in a PR for the falco chart to keep commits and merges separate?

You're totally right, I answered too quickly (again), sorry. I'll stop answering to Github issues from phone in a train 😅

**Review by Issif — APPROVED** [review]

**Pull request merged**
