### PR TITLE
docs: fix spelling mistake in falco/values.yaml

### PR DESCRIPTION
**Pull request by oscr**
**What type of PR is this?**

/kind documentation

**Any specific area of the project related to this PR?**

/area falco-chart

**What this PR does / why we need it**:

Fixes a spelling mistake found in the falco helm chart. 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by cpanato — COMMENTED** [review]
thanks!

**Comment by oscr** [comment]
Thank you for the review @cpanato! Much appreciated :pray:

**Comment by Issif** [comment]
To be "mergeable",  you need to bump up the chart version and the changelog.

**Comment by oscr** [comment]
@Issif Thank you for your help! Fixed!

**Comment by leogr** [comment]
Closing and reopening to trigger the CI
/close

**Pull request merged**
