### PR TITLE
falco: add liveness and readiness probes

### PR DESCRIPTION
**Pull request by cpanato**
**What type of PR is this?**
/kind feature

**Any specific area of the project related to this PR?**

/area falco-chart

**What this PR does / why we need it**:

falco: add liveness and readiness probes

**Which issue(s) this PR fixes**:

Fixes https://github.com/falcosecurity/charts/issues/53

**Special notes for your reviewer**:

**Checklist**

- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] CHANGELOG.md updated

### CODE REVIEW

**Review by leogr — COMMENTED** [review]
Hey @cpanato 

Could you rebase and bump the version again, please?

PS
Lovely PR. It SGTM, I will give it a try soon, thank you! :)

**Comment by cpanato** [comment]
@leogr done sorry for the delay

**Comment by leogr** [comment]
> @leogr done sorry for the delay

I did not wait so long, and anyway no need to apologize :smiley_cat:

**Review by leogr — APPROVED** [review]
It works great!

Really thank you for this effort. We finally got the probes :rocket:

**Comment by CashWilliams** [comment]
An impact of this is that our rollout of a daemonset has gone from a few minutes to multiple hours, as ArgoCD is rolling out each pod and then waiting 30 seconds before moving to the next.

**Comment by leogr** [comment]
Have you tried to tweak `falco.readinessProbe.initialDelaySeconds` ?
Depending on your environment, it might be not needed to wait up to 30 seconds. Perhaps a lower value would work for you.
Let us know!

**Comment by CashWilliams** [comment]
I we are evaluating how/if we want to address it. It just caught us off guard when release went from 60 seconds to 3 hours.

**Pull request merged**
