### PR TITLE
feat: allow changing the default revisionHistoryLimit

### PR DESCRIPTION
**Pull request by tberreis**
**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area falco-chart

/area falcosidekick-chart

/area event-generator-chart

**What this PR does / why we need it**:

I want to clean up old replica sets so that these don't appear in metrics, OPA violations, ArgoCD UI and so on.
Therefore I want to overwrite the Kubernetes default revision history limit.

See [Kubernetes Clean up Policy](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#clean-up-policy).

**Which issue(s) this PR fixes**:

N/A

**Special notes for your reviewer**:

**Checklist**

- [x] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] CHANGELOG.md updated

### CODE REVIEW

**Comment by alacuku** [comment]
Hi @tberreis, could you please update each chart's `CHANGELOG.md` files? Thanks!

**Comment by tberreis** [comment]
> Hi @tberreis, could you please update each chart's `CHANGELOG.md` files? Thanks!

Thank you for your feedback @alacuku. I've updated the changelogs.

**Review by alacuku — APPROVED** [review]
/LGTM

Thanks for the PR!

**Comment by alacuku** [comment]
@leogr, PTAL

**Review by leogr — APPROVED** [review]
Nice!

Thank you!

**Pull request merged**
