### PR TITLE
fix(falco): set dnsPolicy to ClusterFirstWithHostNet when gvisor driver is enabled

### LINKED ISSUE #793: dnsPolicy should be set to ClusterFirstWithHostNet in pod template with gVisor driver
Hi,

**Describe the bug**

The dnsPolicy attribute is currently only set to ClusterFirstWithHostNet when the driver kind is `ebpf` and hostNetwork is enabled. https://github.com/falcosecurity/charts/blob/15f97d55f6c2ddbeb6fefbbb4e8f663d835005af/charts/falco/templates/pod-template.tpl#L36-L38

This is due to how dnsPolicy behaves when hostNetwork is true (https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy)

> "ClusterFirstWithHostNet": For Pods running with hostNetwork, you should explicitly set its DNS policy to "ClusterFirstWithHostNet". Otherwise, Pods running with hostNetwork and "ClusterFirst" will fallback to the behavior of the "Default" policy."

The "Default" policy uses the DNS resolve configuration from the node, this effectively isolate the pod from resolving the IP of other pods/services on the cluster. 

Since the dnsPolicy attribute is not set when the driver is gVisor, but the hostNetwork attribute is. This causes dnsPolicy to fallback to this Default mode. 

https://github.com/falcosecurity/charts/blob/15f97d55f6c2ddbeb6fefbbb4e8f663d835005af/charts/falco/templates/pod-template.tpl#L60-L63

This is an issue especially when you enable the http output to falcosidekick, because the URL is automatically set to `falco-falcosidekick:2801` and fails to lookup, causing an issue similar to https://github.com/falcosecurity/falco/issues/3142.

**How to reproduce it**

Deploy falco with the gVisor driver, and the falcosidekick pod enabled.

Example values file:
```YAML
falcosidekick:
  enabled: true
driver:
  enabled: true
  kind: gvisor
  gvisor:
    enabled: true
````

**Expected behaviour**

`dnsPolicy` should be set to `ClusterFirstWithHostNet` when `driver.kind: gvisor`

### PR DESCRIPTION
**Pull request by NoOverflow**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area falco-chart

**What this PR does / why we need it**:

This PR modify the helm chart for Falco to set the `dnsPolicy` of the falco pod to `ClusterFirstWithHostNet` when the gVisor driver is enabled.

This is needed because right now, the dnsPolicy falls back to the `Default` mode of Kubernetes (see https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy) as the falco pod runs with `hostNetwork` set to true when gVisor is enabled https://github.com/falcosecurity/charts/blob/15f97d55f6c2ddbeb6fefbbb4e8f663d835005af/charts/falco/templates/pod-template.tpl#L60-L63

This is an issue as this `Default` mode uses the node DNS servers, and not the Kubernetes cluster DNS server, causing all lookups to *.cluster.local to fail. 

For example, this breaks the falco sidekick integration as it tries to resolve `falco-falcosidekick` (or `falco-falcosidekick.svc.cluster.local` if `falcosidekick.fullfqdn` is set to true)

https://github.com/falcosecurity/charts/blob/15f97d55f6c2ddbeb6fefbbb4e8f663d835005af/charts/falco/templates/_helpers.tpl#L140-L144

Setting `dnsPolicy` to `ClusterFirstWithHostNet` shouldn't cause breaking changes as this mode fall backs to the node's DNS servers if the request is not for a `.cluster.local` domain. 

**Which issue(s) this PR fixes**:

Fixes #793 

**Special notes for your reviewer**:

None

**Checklist**

None applicable

### CODE REVIEW

**Comment by leogr** [comment]
@NoOverflow, thank you for this PR!

It seems good to me, I just summon @LucaGuerra (who made the gVisor support) for a second look.

**Comment by NoOverflow** [comment]
(For clarity purposes)

- dnsPolicy: ClusterFirst (falls back to default mode since hostNetwork==true)

```
root@azure-k8s-local-worker-cgzez4:/# cat /etc/resolv.conf
search falco.svc.cluster.local svc.cluster.local cluster.local openstacklocal
nameserver 100.64.0.10
options ndots:5
root@azure-k8s-local-worker-cgzez4:/# curl http://falco-falcosidekick:2801
Please send with post http method
```

- dnsPolicy: ClusterFirstWithHostNet 
```
root@azure-k8s-local-worker-cgzez4:/# cat /etc/resolv.conf
search openstacklocal
nameserver 172.16.1.130
root@azure-k8s-local-worker-cgzez4:/# curl http://falco-falcosidekick:2801
curl: (6) Could not resolve host: falco-falcosidekick
```

**Comment by LucaGuerra** [comment]
> I just summon @LucaGuerra 

LGTM, thank you so much for this @NoOverflow ! 🙏 

@leogr and chart masters, could you assist with linting errors and CI?

**Comment by NoOverflow** [comment]
Bumped the chart version to 4.16.2, updated the changelog (and blundered a commit by forgetting to `Signed-off-by` 😄) 

/kind chart-release

**Comment by alacuku** [comment]
Hey @NoOverflow, please run `make docs` to update the chart version in the docs.

**Pull request merged**
