### PR TITLE
Expose Falco controller annotations

### PR DESCRIPTION
**Pull request by cynthiabaran**
**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area falco-chart

**What this PR does / why we need it**:

It exposes controller's annotations in the `values.yaml` file. This might be useful for some production environments that require specific annotations.

**Checklist**
- [ ] Variables are documented in the README.md
- [x] CHANGELOG.md updated

### CODE REVIEW

**Comment by cynthiabaran** [comment]
hey @Issif , thanks for the reply

I'm not sure where to document the new variable in README, aparently they're only documented in comments in the `values.yaml` file itself, and I did that. 

Please let me know if there's something else I need to do.

**Comment by Issif** [comment]
> hey @Issif , thanks for the reply
> 
> I'm not sure where to document the new variable in README, aparently they're only documented in comments in the `values.yaml` file itself, and I did that.
> 
> Please let me know if there's something else I need to do.

You're right, updating the values.yaml is enough. Your commits must me be signed to be accepted, I'm approving when it's done

**Review by Issif — APPROVED** [review]

**Comment by bryanasdev000** [comment]
Sorry to ping a closed issue, but I think some PR messed with changelog, as there is two entries for controller.annotations on https://github.com/falcosecurity/charts/blame/master/falco/CHANGELOG.md, one for 2.5.2 and other for 2.4.7.

**Comment by bryanasdev000** [comment]
maybe related to https://github.com/falcosecurity/charts/pull/449

**Pull request merged**
