### PR TITLE
Fix running of k8saudit actions

### PR DESCRIPTION
**Pull request by cam-at-tactiq**
**What type of PR is this?**

/kind bug

/kind chart-release

/area event-generator-chart

**What this PR does / why we need it**:

Currently users who follow the [example config given here](https://github.com/falcosecurity/charts/blob/ba95f4cbf29a66727535c9460aa8b4f6a778b1f1/charts/event-generator/README.md?plain=1#L85) will see event-generator fail to start.

That's because the rules that match that regexp will only run when the `--all` [flag is provided](https://github.com/falcosecurity/event-generator/blob/7b0dab5d35e270084e84f2ba2156ae385feea3b6/docs/event-generator_run.md?plain=1#L25) because they are [marked as disabled](https://github.com/falcosecurity/event-generator/blob/main/events/k8saudit/yaml_disabled.go).

**Which issue(s) this PR fixes**:
* https://github.com/falcosecurity/charts/issues/723
* https://github.com/falcosecurity/event-generator/issues/212

Fixes #

**Special notes for your reviewer**:

This is my first contribution in Falcosecurity, please let me know if there is more I can do to make this as smooth as possible for review/acceptance.

**Checklist**

- [x] Chart Version bumped
- [x] CHANGELOG.md updated

### CODE REVIEW

**Comment by alacuku** [comment]
Hey @cam-at-tactiq, thanks for the PR. Could you please update the docs as stated here: https://github.com/falcosecurity/charts#contributing?

**Comment by cam-at-tactiq** [comment]
> Hey @cam-at-tactiq, thanks for the PR. Could you please update the docs as stated here: https://github.com/falcosecurity/charts#contributing?

Hi, what changes would. you expect to see in the docs? This PR bumps the chart version and updates the changelog, but doesn't change anything user facing. 

The examples given in the [event-generator docs](https://github.com/falcosecurity/charts/tree/master/charts/event-generator#deployment-modes-in-k8s) will work with this change whereas before they don't. See #723

**Comment by alacuku** [comment]
It would help if you ran `make docs`, automatically updating the docs and fixing the broken  CI.

**Comment by cam-at-tactiq** [comment]
> It would help if you ran `make docs`, automatically updating the docs and fixing the broken CI.

Done, ty

**Review by alacuku — APPROVED** [review]
/lgtm

**Pull request merged**
