### PR TITLE
Add ci helm testing

### PR DESCRIPTION
**Pull request by cpanato**
**What type of PR is this?**
/kind feature

**Any specific area of the project related to this PR?**

**What this PR does / why we need it**:
- This PR introduces a new CI job to test the installation of the helm charts and if the chart has testing templates it will run as well
- Also add a shell checker to validate the shell scripts

/assign @leogr @leodido 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Checklist**

- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] CHANGELOG.md updated

### CODE REVIEW

**Comment by cpanato** [comment]
follow up actions:
- I saw the falcosidekick is broken, will fix that
- add the required GitHub status in prow
- replace the lint to use the CT tool instead of the helm lint, the CT test more things

**Review by leogr — APPROVED** [review]
Hey @cpanato 

Really thank you for this PR!

I'm not 100% sure if `changed=$(docker_exec ct list-changed)` works the same way the release script does, but I believe we can fix it later eventually (likely we can use the same command in the release script too).

So I think it worth to give it a try, and since I don't see any other issue just approved :)

**Comment by leogr** [comment]
PS I'm also opening an issue for missing TODOs

**Comment by cpanato** [comment]
the ct command is recommended to deal with the charts repo :)
I can work to replace that and make more standard script if you like @leogr

**Pull request merged**
