### PR TITLE
bump up version of falcosidekick chart for updating falcosidekick-ui image version

### PR DESCRIPTION
**Pull request by Issif**
Signed-off-by: Issif <issif_github@gadz.org>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> If this PR will release a new chart version please make sure to also uncomment the following line:

/kind chart-release

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area falco-chart

> /area falco-exporter-chart

/area falcosidekick-chart

**What this PR does / why we need it**:

update charts for using v1.0.1 version for falcosidekick-ui

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Checklist**

- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] CHANGELOG.md updated

### CODE REVIEW

**Comment by leogr** [comment]
Hey @Issif 

could you rebase, please?
Once done, I'm ready to approve :)

**Comment by Issif** [comment]
> Hey @Issif
> 
> could you rebase, please?
> Once done, I'm ready to approve :)

done, but the linting is still KO, it's because I tried to update both charts with one PR 😓

**Comment by leogr** [comment]
> > Hey @Issif
> > could you rebase, please?
> > Once done, I'm ready to approve :)
> 
> done, but the linting is still KO, it's because I tried to update both charts with one PR

As discussed we have to split this PR into two, since the dependency must be already present when bumping the dependant.

**Comment by Issif** [comment]
> > > Hey @Issif
> > > could you rebase, please?
> > > Once done, I'm ready to approve :)
> > 
> > 
> > done, but the linting is still KO, it's because I tried to update both charts with one PR
> 
> As discussed privately we have to split this PR into two, since the dependency must be already present when bumping the dependant.

I need to find time for, but I'll do it for sure. Thanks.

**Pull request closed without merging**
