### PR TITLE
Fix/issue 376

### LINKED ISSUE #376: Falco helm chart priorityClassName value
**Describe the bug**

When configuring priorityClassName on Falco helm chart there's a divergence between values.yaml name and templates/pod-template.yaml.

[In values.yaml](https://github.com/falcosecurity/charts/blob/falco-2.0.4/falco/values.yaml#L44)
podPriorityClassName:

[In templates/pod-template.tpl](https://github.com/falcosecurity/charts/blob/falco-2.0.4/falco/templates/pod-template.tpl#L30)
{{- if .Values.priorityClassName }}
  priorityClassName: {{ .Values.priorityClassName }}
{{- end }}

**How to reproduce it**

**Expected behaviour**

values.yaml and pod-template.yaml should have the same value name.

**Screenshots**

**Environment**

- Falco version: falco-2.0.4

- System info: N/A

- Cloud provider or hardware configuration: N/A
- OS: N/A

- Kernel: N/A

- Installation method: Kubernetes

**Additional context**

### PR DESCRIPTION
**Pull request by enmuro**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> If this PR will release a new chart version please make sure to also uncomment the following line:

/kind chart-release

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area falco-chart

> /area falco-exporter-chart

> /area falcosidekick-chart

> /area event-generator-chart

**What this PR does / why we need it**:
Fixes pod-template value name for podPriorityClassName

**Which issue(s) this PR fixes**:

Fixes #376 

**Special notes for your reviewer**:

**Checklist**

- [x] Chart Version bumped
- [x] CHANGELOG.md updated

### CODE REVIEW

**Comment by alacuku** [comment]
Hi @enmuro, thanks for the PR! Could you please add the DCO? You can find more information [here](https://github.com/falcosecurity/.github/blob/master/CONTRIBUTING.md#developer-certificate-of-origin)

**Comment by enmuro** [comment]
Hi, I've added DCO. sorry I'm new to PRs

**Comment by alacuku** [comment]
Hi @enmuro, as @poiana suggested you need rebase and squash/drop some commits. Instruction can be found [here](https://github.com/kubernetes/community/blob/master/contributors/guide/github-workflow.md#4-keep-your-branch-in-sync).
An easier way could be to close this PR and open a new one from a new branch with you original commit containing the DCO. 
Let me know if you need help!

**Comment by enmuro** [comment]
I will create a new one, thank you

**Pull request closed without merging**
