### PR TITLE
Fix typo in values-k8audit file

### PR DESCRIPTION
**Pull request by AliyevH**
Fixes # Typo

### CODE REVIEW

**Review by alacuku — DISMISSED** [review]
Thanks, @AliyevH.

/LGTM

**Comment by alacuku** [comment]
You need to bump the chart version and add the changelogs.

**Comment by AliyevH** [comment]
@alacuku Thanks for reply. Done

**Comment by leogr** [comment]
Closing and reopening to trigger the CI

**Review by leogr — APPROVED** [review]

**Pull request merged**
