### PR TITLE
Add falco-exporter pod annontations

### PR DESCRIPTION
**Pull request by nonamef**
What type of PR is this?**
> /kind feature

**Any specific area of the project related to this PR?**
> /area falco-exporter-chart

**What this PR does / why we need it**:
Add support for DaemonSet annotations

**Which issue(s) this PR fixes**:
Fixes https://github.com/falcosecurity/charts/issues/201

### CODE REVIEW

**Review by leogr — COMMENTED** [review]
Hey @nonamef 

Thank you for this contribution!

It SMGT but we need the commit to be signed-off, PTAL :point_down: 
https://github.com/falcosecurity/.github/blob/master/CONTRIBUTING.md#developer-certificate-of-origin

Moreover, could you please bump the chart version?

Thanks in advance

**Comment by sergeyshaykhullin** [comment]
@nonamef Can you please signoff your commits and bump chart version?

```
git commit --amend --no-edit --signoff
git push --force-with-lease origin feature-201-falco-exporter-annontations
```

/remove-lifecycle stale

**Comment by leogr** [comment]
Ping @nonamef :)

**Comment by leogr** [comment]
> @leogr if this is something we still want i will rebase and push the necessary things in this pr, if you are ok with that

Hey @cpanato 

Since the original author is not responding anymore, I believe it would be better to open another PR (we cannot sign off on behalf of the author). Anyway, to be fair, we could give credits by adding the original author as a co-author. WDYT?

**Comment by cpanato** [comment]
@leogr done here https://github.com/falcosecurity/charts/pull/289

we can close this 
/close

**Pull request closed without merging**
