### PR TITLE
Feat: Set grafana dashboard folder

### PR DESCRIPTION
**Pull request by hehuels**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

/kind feature

> If this PR will release a new chart version please make sure to also uncomment the following line:

> /kind chart-release

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area falco-chart

/area falco-exporter-chart

> /area falcosidekick-chart

> /area event-generator-chart

**What this PR does / why we need it**:
Adds the functionality to pack the dashboard into a folder. (Grafana Browser)

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Checklist**

- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] CHANGELOG.md updated

### CODE REVIEW

**Review by cpanato — CHANGES_REQUESTED** [review]
please bump the chart version

**Review by leogr — APPROVED** [review]

**Comment by leogr** [comment]
> please bump the chart version

@cpanato PTAL again

**Comment by leogr** [comment]
@cpanato could you review again and remove the "change request" pls?
Otherwise, the PR can't be merged. Thank you!

**Review by cpanato — APPROVED** [review]
/lgtm

sorry for the delay

**Pull request merged**
