### PR TITLE
Bump Falco-exporter image version to 0.8.3

### PR DESCRIPTION
**Pull request by hardwarefresser**
**What type of PR is this?**
/kind feature
/kind chart-release

**Any specific area of the project related to this PR?**
/area falco-exporter-chart

**What this PR does / why we need it**:
Falco exporter version upgrade to v0.8.3

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Checklist**
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] CHANGELOG.md updated

### CODE REVIEW

**Review by cpanato — DISMISSED** [review]
thanks
/lgtm

**Comment by hardwarefresser** [comment]
Sorry! https://github.com/falcosecurity/charts/pull/491/commits/3f404b139b2e5c61d66c6d96d5e7fe7d7b9610f7 was a mistake. Will rebase tomorrow.

**Comment by hardwarefresser** [comment]
rebased. Commits should be clean again. Please excuse the confusion!

**Review by leogr — APPROVED** [review]
Thank you :pray:

**Pull request merged**
