### PR TITLE
Allow additional service-ui annotations

### PR DESCRIPTION
**Pull request by igoritos22**
Signed-off-by: igoritos22 <igoritos_22@hotmail.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

/kind feature

> If this PR will release a new chart version please make sure to also uncomment the following line:

/kind chart-release

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area falco-chart

> /area falco-exporter-chart

/area falcosidekick-chart

**What this PR does / why we need it**:
Allow add annotations to falcosidekick-ui service 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Checklist**

- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] CHANGELOG.md updated

### CODE REVIEW

**Review by Issif — COMMENTED** [review]
Hello,

Can you also update the values.yaml and README please.

**Comment by igoritos22** [comment]
@Issif, update done!

**Review by Issif — DISMISSED** [review]
:+1:

**Comment by igoritos22** [comment]
@Issif, I can't understand why ci/circleci lint charts is failing. Can youu help me ?

**Comment by Issif** [comment]
Here the result of lint from Circle-CI:

```
falcosidekick/values.yaml
  396:70    error    trailing spaces  (trailing-spaces)
  438:3     error    no new line character at the end of file  (new-line-at-end-of-file)
  438:1     error    trailing spaces  (trailing-spaces)
```

**Review by Issif — APPROVED** [review]

**Pull request merged**
