### PR TITLE
removed maxSurge reference from values.yaml

### PR DESCRIPTION
**Pull request by anthony-alessi-acquia**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> If this PR will release a new chart version please make sure to also uncomment the following line:

> /kind chart-release

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area falco-chart

> /area falco-exporter-chart

> /area falcosidekick-chart

**What this PR does / why we need it**:

removes an invalid suggestion of setting maxSurge in a daemonset pod on line 77 of values.yaml

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Checklist**

- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] CHANGELOG.md updated

### CODE REVIEW

**Comment by leogr** [comment]
Hey,

Thanks for finding and fixing this! :)

We just need two more things to accept the PR:

- could you [sign off](https://github.com/falcosecurity/.github/blob/master/CONTRIBUTING.md#developer-certificate-of-origin) the commit, please?
- it is also necessary to bump the chart version (that makes the CI happy :smile_cat: )

Otherwise, it looks good to me :+1:

**Comment by anthony-alessi-acquia** [comment]
@leogr I signed off on the commit but thought of a quick question. Is there any documentation on how to bump the chart version? Specifically, which files need the version bump edit and what version would I make the new chart? Thanks.

**Comment by Issif** [comment]
> @leogr I signed off on the commit but thought of a quick question. Is there any documentation on how to bump the chart version? Specifically, which files need the version bump edit and what version would I make the new chart? Thanks.

You need to bump up this version up to `1.15.7` https://github.com/falcosecurity/charts/blob/413a091a42525a4d9114e42f94e88b92e535b0b3/falco/Chart.yaml#L3 

and update the changelog: https://github.com/falcosecurity/charts/blob/master/falco/CHANGELOG.md#change-log

**Comment by leogr** [comment]
> @leogr I signed off on the commit but thought of a quick question. Is there any documentation on how to bump the chart version? Specifically, which files need the version bump edit and what version would I make the new chart? Thanks.

I've rebased the PR for you to resolve the conflict and added a changelog line too. It should be fine now (I'm going to approve once the CI passes).

Regarding the documentation, I realized we haven't well explained the process and I understand it can be confusing for newcomers. These kinds of feedback are valuable for us, so thank you for pointing that out :pray: 

PS
I will try to fix the documentation soon.

**Review by leogr — APPROVED** [review]

**Pull request merged**
