### PR TITLE
Add Google Chat support for Falco Sidekick

### PR DESCRIPTION
**Pull request by KeisukeYamashita**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

/kind feature

> If this PR will release a new chart version please make sure to also uncomment the following line:

/kind chart-release

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area falco-chart

> /area falco-exporter-chart

/area falcosidekick

**What this PR does / why we need it**:

I added update regarding the update in Falco Sidekick [Add Google Chat support](https://github.com/falcosecurity/falcosidekick/pull/107).

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

Please don't merge until the new release has published. Thanks in advance.

**Checklist**

- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] CHANGELOG.md updated

### CODE REVIEW

**Comment by leogr** [comment]
Hey @KeisukeYamashita 

just a tip, you can use the `wip:` prefix instead of `[DON'T MERGE]`. Our beloved bot @poiana disallows merging until `wip:` is present in the title :)

**Comment by Issif** [comment]
@KeisukeYamashita thank you a lot.

Do you think you'll have enough time for adding GCP PubSub in another PR? I didn't had time for yet (see last releases).

🙏

**Comment by KeisukeYamashita** [comment]
@Issif Yes, I do and I will be happy to work on it!😎

**Comment by KeisukeYamashita** [comment]
@leogr Thank you a lot! I will remove it once the new release publish🙏

**Comment by Issif** [comment]
@KeisukeYamashita I'll prepare release 2.18.0 of falcosidekick asap. 👍

**Comment by KeisukeYamashita** [comment]
Thank you for your quick work as always 🙇

**Comment by KeisukeYamashita** [comment]
@Issif  Thank you for releasing `0.1.30` 😄 
I resolved the conflicts and now it's ready 🙇

**Comment by Issif** [comment]
@KeisukeYamashita Thank you a lot with your help, feel free to contribute at anytime, your PR was really clean

**Review by Issif — APPROVED** [review]

**Comment by KeisukeYamashita** [comment]
Thank you for your quick super work 🙇  
I would be happy to contribute to this nice project, please request me any 😄

**Pull request merged**
