### PR TITLE
Update links in README

### PR DESCRIPTION
**Pull request by marcelbirkner**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

Updates links in main README due to restructuring the chart directory

### CODE REVIEW

**Review by Issif — DISMISSED** [review]

**Review by cpanato — CHANGES_REQUESTED** [review]
please squash the commits and signoff

**Review by cpanato — CHANGES_REQUESTED** [review]
please use rebase and not merge

**Comment by leogr** [comment]
> please use rebase and not merge

Hey @cpanato 

I've rebased this PR. The merge commit is now gone. PTA: and approve eventually :pray:

**Review by cpanato — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
