### PR TITLE
Align falco.rulesFile in README with values.yaml

### LINKED ISSUE #230: falco.rulesFile has a different value in README and in values.yaml
**Describe the bug**

`falco.rulesFile` has a different value in `README` and in `values.yaml`

**How to reproduce it**

N/A

**Expected behaviour**

`falco.rulesFile` has the same value in `README` and in `values.yaml`

**Screenshots**

N/A

**Environment**

N/A

- Falco version:
falco chart version: `master` (6863f90b50f37d5c793c8a9b4147b7c2e138e1a2 at the time of writing of this issue)

- System info:

N/A

**Additional context**

### PR DESCRIPTION
**Pull request by pmalek-sumo**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area falco-chart

**What this PR does / why we need it**:

Align `falco.rulesFile` in README with values.yaml 

**Which issue(s) this PR fixes**:

Fixes #230

### CODE REVIEW

**Comment by pmalek-sumo** [comment]
> Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.
> 
> 📝 **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/charts/blob/master/CONTRIBUTING.md) to update your commits with the DCO**

The link to contributing guide seems dead

**Review by leogr — COMMENTED** [review]
Hi, 

thank you for opening this PR!

However, it seems to me `application_rules.yaml` is not enabled by default in Falco:
https://github.com/falcosecurity/falco/blob/master/falco.yaml#L30-L34

Maybe we should update the documentation instead.

@falcosecurity/charts-maintainers wdyt?

**Comment by pmalek-sumo** [comment]
> @pmalek-sumo: PR needs rebase.

Done.

**Comment by pmalek-sumo** [comment]
Can this get merged? (obviously granted that I rebase my changes but I'm not sure this still has a chance of being accepted)

**Comment by leogr** [comment]
> Can this get merged? (obviously granted that I rebase my changes but I'm not sure this still has a chance of being accepted)

Hi,

my only concern is that `application_rules.yaml` is not enabled by default in Falco (see my previous comment). I would rather fix the README, to reflect the current status. Unless there's a need that I'm missing (in such case, I would change this in Falco first and then in the chart anyway). Am I missing anything?

However, just my two cents :smile_cat: 
So, feel free to discuss with other maintainers and the community if you feel this is really needed.

**Comment by pmalek-sumo** [comment]
> > Can this get merged? (obviously granted that I rebase my changes but I'm not sure this still has a chance of being accepted)
> 
> Hi,
> 
> my only concern is that `application_rules.yaml` is not enabled by default in Falco (see my previous comment). I would rather fix the README, to reflect the current status. Unless there's a need that I'm missing (in such case, I would change this in Falco first and then in the chart anyway). Am I missing anything?
> 
> However, just my two cents 😸
> So, feel free to discuss with other maintainers and the community if you feel this is really needed.

@leogr Done :) Please check

**Review by leogr — APPROVED** [review]
Thank you!

**Pull request merged**
