### PR TITLE
vote: docs(OWNERS): add alacuku (Aldo Lacuku) to approvers

### PR DESCRIPTION
**Pull request by alacuku**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

/kind documentation

> /kind failing-test

> /kind feature

> If this PR will release a new chart version please make sure to also uncomment the following line:

> /kind chart-release

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area falco-chart

> /area falco-exporter-chart

> /area falcosidekick-chart

> /area event-generator-chart

> /area k8s-metacollector

**What this PR does / why we need it**:

Proposing myself as falcoctl maintainer as per 2024-03-27 community call discussion.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
/hold until a week has passed or the majority is reached (as per our governance)
**Checklist**

- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] CHANGELOG.md updated

### CODE REVIEW

**Comment by Issif** [comment]
+1 for me :thu

**Comment by cpanato** [comment]
+1

**Comment by leogr** [comment]
Welcome onboard :) 
/unhold

**Review by leogr — APPROVED** [review]

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
