### PR TITLE
remove duplicated webhook block in values.yaml

### LINKED ISSUE #88: Duplicate entry in values of falcosidekick
The parameters for `webhook` output are duplicated, see : https://github.com/falcosecurity/charts/blob/204485654d288e9ba8a92c3290edd41a1b8a304b/falcosidekick/values.yaml#L125

**Expected behaviour**

Remove useless block

**Screenshots**

N/A

**Environment**

N/A

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by Issif**
Signed-off-by: thomas.labarussias <thomas.labarussias@qonto.eu>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> If this PR will release a new chart version please make sure to also uncomment the following line:

/kind chart-release

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area falco-chart

> /area falco-exporter-chart

/area falcosidekick

**What this PR does / why we need it**:

A duplicated block for `webhook` is in values.yaml

**Which issue(s) this PR fixes**:

Fixes #88 

**Special notes for your reviewer**:

**Checklist**

- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] CHANGELOG.md updated

### CODE REVIEW

**Review by leogr — CHANGES_REQUESTED** [review]
Hey @Issif 

I still see `0.1.23` in the [Chart.yaml](https://github.com/falcosecurity/charts/blob/c2a52747fd613e93ad31a9d875409d524286751e/falcosidekick/Chart.yaml#L6). 

Can you update that, please?

**Comment by Issif** [comment]
@leogr fixed. thanks

**Comment by Issif** [comment]
@leogr wait, my sign-off are wrong, I need to change that.

**Comment by Issif** [comment]
@leogr it's fixed 👍

**Review by leogr — APPROVED** [review]
LGTM

Thank you!

**Pull request merged**
