### PR TITLE
fix: mount client-certs-volume only if certs.existingClientSecret is …

### PR DESCRIPTION
**Pull request by yohboy**
…defined

**What type of PR is this?**
/kind bug

**Any specific area of the project related to this PR?**
/area falco-chart

**What this PR does / why we need it**:

Fix a bug where the chart tries to mount a volume that does not exist.  
The check to mount the volume is wrong and should check for the `.Values.certs.existingClientSecret` value instead of `.Values.certs.existingSecret`.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Checklist**

- [x] Chart Version bumped
- [x] CHANGELOG.md updated

### CODE REVIEW

**Comment by alacuku** [comment]
Hi @johboy, please run `make docs` to update the chart version in the docs.

**Comment by yohboy** [comment]
Hi @alacuku , done ✅ 
Thanks

**Review by alacuku — COMMENTED** [review]
/lgtm

**Review by alacuku — APPROVED** [review]

**Pull request merged**
