### PR TITLE
Add imagePullSecretes to the Helm chart

### PR DESCRIPTION
**Pull request by arminc**
Signed-off-by: Armin armin@coralic.nl
What type of PR is this?

/kind feature
Any specific area of the project related to this PR?

/area helm

What this PR does / why we need it:

Adding the imagePullSecrets to the Helm deployments to allow authenticated Docker registries.

### CODE REVIEW

**Review by leogr — COMMENTED** [review]
Thank you @arminc !

SGTM, just waiting for @Issif approval.


/kind chart-release
/area falcosidekick-chart

**Review by Issif — APPROVED** [review]

**Review by leogr — APPROVED** [review]

**Comment by leogr** [comment]
Too late, I will fix it in a new PR eventually

**Pull request merged**
