### PR TITLE
[fix] Helm : Grafana dashboard for k8s metacollector

### PR DESCRIPTION
**Pull request by nlamirault**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> If this PR will release a new chart version please make sure to also uncomment the following line:

> /kind chart-release

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area falco-chart

> /area falco-exporter-chart

> /area falcosidekick-chart

> /area event-generator-chart

/area k8s-metacollector

**What this PR does / why we need it**:

Before PR:

Falco-Meta-Collector-security-Dashboards-Grafana

After:

Falco-Meta-Collector-security-Dashboards-Grafana (1)

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Checklist**

- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] CHANGELOG.md updated

### CODE REVIEW

**Comment by Issif** [comment]
Hi,

To make this PR valid for the CI, please:
- bump up the chart version
- update the changelog
- run `make docs-k8s-metacollector`

Also, be sure to have rebased on master before and squashed your commits.

**Comment by alacuku** [comment]
Hi @nlamirault, thanks for the contribution!

Please, update the chart version, docs, and changelog. Once you have done we can merge the changes.

**Comment by alacuku** [comment]
hi @nlamirault, could you please rebase your branch on top of main?

**Comment by alacuku** [comment]
hey @nlamirault, sorry to bother you, but a rebase is still needed here.

**Comment by leogr** [comment]
closing and reopening this to trigger the CI
/close

**Comment by leogr** [comment]
This still need to be rebased (with no merge commit)

**Comment by leogr** [comment]
I've rebased this PR and fixed the readme. I'm just double-checking right now, then I will approve.

Thank you for this contribution!

**Review by leogr — APPROVED** [review]

**Pull request merged**
