### PR TITLE
fix aad pod identity

### PR DESCRIPTION
**Pull request by dza89**
Bug

### CODE REVIEW

**Comment by dza89** [comment]
Do i have to make a seperate pull request to bump the sidekick in the falco chart? That seems to be the mistake.

**Comment by leogr** [comment]
> Do i have to make a seperate pull request to bump the sidekick in the falco chart? That seems to be the mistake.

You can apply the fix and bump the version in the same PR. 

Just two small things:
- The sign-off is missing for the last commit. Could you fix that?
- Could you update the changelog too?

Then I will approve shortly. If you need any further help, let me know.

Thank you!

**Comment by dza89** [comment]
@leogr 
Done

**Comment by dza89** [comment]
It's still failing the e2e curl: (56) SSL read: error:00000000:lib(0):func(0):reason(0), errno 104

**Comment by leogr** [comment]
> It's still failing the e2e curl: (56) SSL read: error:00000000:lib(0):func(0):reason(0), errno 104

It was a temporary CI issue, I relaunched the job and now it works.

**Review by leogr — APPROVED** [review]

**Comment by leogr** [comment]
PS
Thank you again!

**Pull request merged**
