### PR TITLE
NOTES.txt: Fix links

### PR DESCRIPTION
**Pull request by schnatterer**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

/kind documentation

> /kind failing-test

> /kind feature

> If this PR will release a new chart version please make sure to also uncomment the following line:

/kind chart-release

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area falco-chart

> /area falco-exporter-chart

> /area falcosidekick-chart

> /area event-generator-chart

> /area k8s-metacollector

**What this PR does / why we need it**:
Fixes links in output after falco install without sidekick

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Checklist**

- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] CHANGELOG.md updated

### CODE REVIEW

**Review by Issif — COMMENTED** [review]
Thanks for the fix. To pass the CI, you need to bump up the chart version and update the changelog too.

**Comment by alacuku** [comment]
Hi @schnatterer, could you please run `make docs-falco` and then push again?

**Comment by schnatterer** [comment]
Thanks, done. 
The option in the PR template `/kind chart-release` lead me to believe you might not release every change.  
I had a look at the `CONTRIBUTING.md`  but missed the `make docs` mentioned in `README.md`.
You could adapt those in the PR template to make it easier for new contributors :slightly_smiling_face:

**Review by alacuku — APPROVED** [review]
/LGTM

**Comment by alacuku** [comment]
@Issif, con you have a look?

**Pull request merged**
