### PR TITLE
Fix comment in values.yaml

### PR DESCRIPTION
**Pull request by mike-stewart**
Signed-off-by: Mike Stewart <2521245+mike-stewart@users.noreply.github.com>

**What type of PR is this?**

/kind documentation

**Any specific area of the project related to this PR?**

/area falco-chart

**What this PR does / why we need it**: Fixes a backwards comment in falco values.yaml.

**Which issue(s) this PR fixes**: Not logged.

**Special notes for your reviewer**:

**Checklist**

- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] CHANGELOG.md updated

### CODE REVIEW

**Comment by alacuku** [comment]
Hi @mike-stewart, thanks for the fix. Could you please run a `make docs` in the falco folder? Furthermore, you need to bump the version of the chart and update the CHANGELOG.md otherwise the CI will complain about it.

**Comment by mike-stewart** [comment]
@leogr @alacuku Updated, this should be good to go.

**Review by alacuku — DISMISSED** [review]
/LGTM

**Comment by leogr** [comment]
I'll fix the conflicting files and approve this PR soon, thank you!

**Review by leogr — APPROVED** [review]

**Pull request merged**
