### PR TITLE
update(falco): update chart to 4.8.0 for Falco 0.38.2

### PR DESCRIPTION
**Pull request by LucaGuerra**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind feature

> If this PR will release a new chart version please make sure to also uncomment the following line:

/kind chart-release

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area falco-chart

**What this PR does / why we need it**:

See https://github.com/falcosecurity/falco/issues/3289

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Checklist**

- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] CHANGELOG.md updated

### CODE REVIEW

**Comment by LucaGuerra** [comment]
/hold

for release

**Review by alacuku — APPROVED** [review]
/lgmt

**Pull request merged**
