### PR TITLE
[Falco] Fix containerd socket path in args

### PR DESCRIPTION
**Pull request by Annegies**
Signed-off-by: Annegies van 't Zand <ace.vtzand@gmail.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> If this PR will release a new chart version please make sure to also uncomment the following line:

> /kind chart-release

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area falco-chart

> /area falco-exporter-chart

> /area falcosidekick-chart

**What this PR does / why we need it**:
On containerd nodes the k8s.*.* fields weren't being filled. Turned out the socket path was wrong in the args

**Which issue(s) this PR fixes**:
None

Fixes #

**Special notes for your reviewer**:

**Checklist**

- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] CHANGELOG.md updated

### CODE REVIEW

**Review by leogr — CHANGES_REQUESTED** [review]
Thank you for your effort, but unfortunately, adding the `/host` prefix seems to be not correct to me.
Indeed, it was removed (see https://github.com/falcosecurity/charts/commit/42688ae0879b346b0a10e7e0069632b57452ee75 ) since the prefix is automatically added by Falco internally.

The prefix automation is controlled by the `HOST_ROOT` env var :point_down: 
https://github.com/falcosecurity/falco/blob/f140cdfd6891116276001b3d4e429023b48cdb10/docker/falco/Dockerfile#L12

So I cannot understand how this PR would solve the issue you reported.
If `/host/run/containerd/containerd.sock` worked for you, then there's something that's not working as expected. If it's the case, provide a reproducible example, please.

Or perhaps, are you using a custom container image that's missing the `HOST_ROOT` env var?

**Comment by Annegies** [comment]
In the daemonset template the volume containerd-socket is mounted at /host/run/containerd/containerd.sock

**Comment by Annegies** [comment]
Hm, had to read your comment twice. 

the HOST_ROOT is indeed /host. I do see it working occasionally indeed.. i saw it working all the time when i changed the path but it tends to be a little shaky anyways. Alright thanks for your response i'll close the PR

**Pull request closed without merging**
