### PR TITLE
new falcosidekick grafana dashboard

### PR DESCRIPTION
**Pull request by cobcan**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

/kind feature

> If this PR will release a new chart version please make sure to also uncomment the following line:

/kind chart-release

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area falco-chart

> /area falco-exporter-chart

> /area falcosidekick-chart

> /area falco-talon

> /area event-generator-chart

> /area k8s-metacollector

**What this PR does / why we need it**:
Adds a new dashboard for the falcosidekick logs using Loki. This dashboard represents alerts/rules by pod.
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

This dashboard needs Grafana, Prometheus and Loki. Also it needs to connect the falcosidekick to Loki.

**Checklist**

- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] CHANGELOG.md updated

### CODE REVIEW

**Comment by alacuku** [comment]
Hey @cobcan, thanks for the contribution!

Can we put the dashboard in the falcosidekick chart?

**Comment by cobcan** [comment]
Yeah sure there is no problem with that, do you want to move it or copy it?

**Comment by Issif** [comment]
> @alacuku Yeah sure there is no problem with that, do you want to move it or copy it?

Move it please. Moreover, can you name your dashboard with refs Falcosidekick and Loki, on my side, I'm working on a dashboard for Falcosidekick with prometheus metrics, both are legit, we just need to be sure it will be clear for the users.

**Comment by alacuku** [comment]
> @alacuku @Issif
> 
> I have seen the falcosidekick chart and now I understand better what you mean.
> 
>     1. I will create a folder called "dashboards" like in the falco chart, and put there de  .json.
> 
>     2. Then I will create a new template for the dashboard configmap and add it to the chart.
> 
>     3. Lastly I will remove the changes done in the falco-chart.
> 
> 
> Please tell me if it makes sense to you. Thanks!!

Yes, that's the way to go! Thanks!

**Pull request closed without merging**
