### PR TITLE
Fix README link to Policy Report documentation

### PR DESCRIPTION
**Pull request by brianirish**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it:**

Updates the link to the policy report output documentation

### CODE REVIEW

**Comment by cpanato** [comment]
Need to bump the chart version

**Comment by brianirish** [comment]
> Need to bump the chart version

Thanks @cpanato I've bumped the chart version. It takes a while for the test check to give a result I guess?

**Comment by Issif** [comment]
You bumped the falco chart version, but not the falcosidekick. Moreover, you need to update the changelog either.

**Comment by brianirish** [comment]
Thanks for the advice @Issif, I have made the appropriate changes as per your comment.

**Comment by Issif** [comment]
Can you remove the changed you made for the falco chart, scope your PR to falcosidekick please

**Comment by brianirish** [comment]
@Issif Completed. Thank you!

**Comment by leogr** [comment]
Merge conflicts arise after merging https://github.com/falcosecurity/charts/pull/586

I'm going to address them, and I will approve.

PS
Thank you for this PR :pray:

**Review by leogr — APPROVED** [review]

**Pull request merged**
