### PR TITLE
Add securityContext to deployments and redis sts

### PR DESCRIPTION
**Pull request by Kostavro**
Signed-off-by: kostas <kostavro@gmail.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

/kind feature

> If this PR will release a new chart version please make sure to also uncomment the following line:

/kind chart-release

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area falco-chart

> /area falco-exporter-chart

/area falcosidekick-chart

**What this PR does / why we need it**:
This PR aims to enable full configuration of pod and container securityContext in the Deployments and StatefulSet of falcosidekick.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
I have not updated the values in `README.md`. They are already outdated and I have been lazy. I would suggest using something helm-docs via a pre-commit hook. If this PR is not merged before I find the time, I will try to sync all of the supported values.

**Checklist**

- [X] Chart Version bumped
- [x] Variables are documented in the README.md
- [X] CHANGELOG.md updated

### CODE REVIEW

**Comment by Issif** [comment]
To avoid this PR to me merged, just add `WIP` in the title. I'll review your changes anyway

**Comment by Kostavro** [comment]
@Issif I have fixed the README.md file. I have updated it with the new values, I have added values that were not added before, removed values that do not exist, fixed default values that were wrong and updated a few descriptions. I also tried to align the cells so that it is easier maintained.
Kindly review.

**Review by Issif — COMMENTED** [review]
Thank you very much, it's a really nice PR, and thanks for the fixes and linting.
Can you just add in the Changelog that it introduces a breaking change for security contexts (I know we don't follow semver for the versions of the Chart and it's bad....)

**Comment by Kostavro** [comment]
Thanks @Issif  :) I believe the changes in the pre-existing securityContext won't break anything, since I have left the pre-set values in the values.yaml. But, if you think they count as breaking changes, we can also update the major version and try to follow semver anyways :D 
Let me know what you think and I will update accordingly.

**Review by Issif — APPROVED** [review]
I'm Ok. thank you.
FYI, we also need to update the dependency in falco Helm chart

**Pull request merged**
