### PR TITLE
fix(exporter): update tolerations

### PR DESCRIPTION
**Pull request by alacuku**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> If this PR will release a new chart version please make sure to also uncomment the following line:

/kind chart-release

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area falco-chart

/area falco-exporter-chart

> /area falcosidekick-chart

> /area event-generator-chart

> /area k8s-metacollector

**What this PR does / why we need it**:

Update the tolerations.

**Which issue(s) this PR fixes**:

Fixes #
#579 
**Special notes for your reviewer**:

**Checklist**

- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] CHANGELOG.md updated

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/lgtm

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by cpanato** [comment]
humm just saw the tests are failing

/lgtm cancel

**Comment by alacuku** [comment]
For some reason the connection test is failing. It seems that the `wget` container is started before the falco exporter pods are ready. 
By running the same test manually after the falco-exporte pods are ready everything works fine.

@cpanato any idea why this is happening?

**Comment by alacuku** [comment]
@cpanato 
Helm v3.10 was not honoring the `--wait & --timeout` flags. Bumped to v3.14.0. Solved the issue.

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
